remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: OM Udvidet 3D Print Kursus
description: Kursusmateriale til avanceret 3D print hos Orange Makers
show_downloads: false

theme_settings:
  header_bg: "#159957"
  header_bg2: "#155799"
  section_headings_color: "#159957"
