remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: OM Udvidet 3D Print Kursus
description: Kursusmateriale til avanceret 3D print hos Orange Makers
show_downloads: false

# Tilpasning af farver og layout
colors:
  header: "#000"
  section: "#333"
  text: "#333"
